"""rename department

Revision ID: 0dc0c5844743
Revises: 703ce22d53bc
Create Date: 2024-09-14 19:52:43.727660

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dc0c5844743"
down_revision = "703ce22d53bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
