"""add Department

Revision ID: 703ce22d53bc
Revises: 316f98294546
Create Date: 2024-09-14 19:49:07.431286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ce22d53bc'
down_revision = '316f98294546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
