"""rename address

Revision ID: cfc9144ed3e0
Revises: 0dc0c5844743
Create Date: 2024-09-14 20:43:54.730450

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfc9144ed3e0"
down_revision = "0dc0c5844743"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
